
--************* Criação de tabelas **************
--** CLIENTE - TIPO - MEDIDA - FORNECDOR - ARTIGO - ENCOMENDA - ENCOMENDA_ARTIGO
--** FACTURA - LINHA DE FACTURA

CREATE TABLE CLIENTE 
   (	ID_CLIENTE VARCHAR2(200) NOT NULL ENABLE, 
	NOME VARCHAR2(50) NOT NULL ENABLE, 
	MORADA VARCHAR2(200) NOT NULL ENABLE, 
	CONTRIBUINTE VARCHAR2(9) NOT NULL ENABLE
   ) ;
  ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLIENTE) ENABLE;

CREATE TABLE ENCOMENDA 
   (	ID_ENCOMENDA NUMBER(*,0) NOT NULL ENABLE, 
      ID_CLIENTE VARCHAR2(200) NOT NULL ENABLE,
      DATA_ENC DATE NOT NULL ENABLE,
      FACTURADA NUMBER(1,0) NOT NULL ENABLE
    ) ;
  ALTER TABLE ENCOMENDA ADD CONSTRAINT PK_ENCOMENDA PRIMARY KEY (ID_ENCOMENDA) ENABLE;
  ALTER TABLE ENCOMENDA ADD CONSTRAINT FK_ENCOMENDA_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
	  REFERENCES CLIENTE (ID_CLIENTE) ENABLE;
    
CREATE TABLE MEDIDA 
   (	COD_MEDIDA NUMBER(*,0) NOT NULL ENABLE, 
      DESCRICAO VARCHAR2(50) NOT NULL ENABLE
    ) ;
  ALTER TABLE MEDIDA ADD CONSTRAINT PK_MEDIDA PRIMARY KEY (COD_MEDIDA) ENABLE;   
  
CREATE TABLE FORNECEDOR 
   (	COD_FORNECEDOR NUMBER(*,0) NOT NULL ENABLE, 
      NOME VARCHAR2(50) NOT NULL ENABLE
    ) ;
  ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY (COD_FORNECEDOR) ENABLE;  
  
CREATE TABLE ARTIGO 
   (	COD_ARTIGO NUMBER(*,0) NOT NULL ENABLE, 
      DESCRICAO VARCHAR2(100) NOT NULL ENABLE,  
      COD_FORNECEDOR NUMBER(9,0) NOT NULL ENABLE,  
      COD_MEDIDA NUMBER(9,0) NOT NULL ENABLE,
      STOCK NUMBER (4,0) NOT NULL ENABLE,
      PRECO NUMBER(4,2) NOT NULL ENABLE, 
      TAXA_IVA NUMBER(4,2) NOT NULL ENABLE
    ) ;
  ALTER TABLE ARTIGO ADD CONSTRAINT PK_ARTIGO PRIMARY KEY (COD_ARTIGO) ENABLE;
  ALTER TABLE ARTIGO ADD UNIQUE (DESCRICAO) ENABLE;
  ALTER TABLE ARTIGO ADD CONSTRAINT FK_ARTIGO_FORNECEDOR FOREIGN KEY (COD_FORNECEDOR)
	  REFERENCES FORNECEDOR (COD_FORNECEDOR) ENABLE;
  ALTER TABLE ARTIGO ADD CONSTRAINT FK_ARTIGO_MEDIDA FOREIGN KEY (COD_MEDIDA)
	  REFERENCES MEDIDA (COD_MEDIDA) ENABLE;  
 
CREATE TABLE ENCOMENDA_ARTIGO 
   (	ID_ENCOMENDA NUMBER(*,0) NOT NULL ENABLE, 
      COD_ARTIGO NUMBER(*,0) NOT NULL ENABLE,
      QUANTIDADE INTEGER NOT NULL ENABLE
    ) ;
  ALTER TABLE ENCOMENDA_ARTIGO ADD CONSTRAINT ENCOMENDA_ARTIGO_PK PRIMARY KEY 
    (ID_ENCOMENDA, COD_ARTIGO) ENABLE;
  ALTER TABLE ENCOMENDA_ARTIGO ADD CONSTRAINT ENCOMENDA_ARTIGO_ENCOMENDA FOREIGN KEY 
    (ID_ENCOMENDA)
	  REFERENCES ENCOMENDA (ID_ENCOMENDA) ENABLE;
  ALTER TABLE ENCOMENDA_ARTIGO ADD CONSTRAINT ENCOMENDA_ARTIGO_ARTIGO FOREIGN KEY (COD_ARTIGO)
	  REFERENCES ARTIGO (COD_ARTIGO) ENABLE;
 
CREATE TABLE FACTURA 
   (	COD_FACTURA NUMBER(*,0) NOT NULL ENABLE, 
      ID_CLIENTE VARCHAR2(200) NOT NULL ENABLE, 
      ID_ENCOMENDA NUMBER(*,0) NOT NULL ENABLE,
      DATA_FACT DATE NOT NULL ENABLE,
      VALOR_SEM_IVA NUMBER NOT NULL ENABLE, 
      VALOR_IVA NUMBER NOT NULL ENABLE, 
      TOTAL NUMBER NOT NULL ENABLE
    ) ;
  ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_PK PRIMARY KEY (COD_FACTURA) ENABLE;
  ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_CLIENTE)
	  REFERENCES CLIENTE (ID_CLIENTE) ENABLE;
  ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_ENCOMENDA FOREIGN KEY (ID_ENCOMENDA)
	  REFERENCES ENCOMENDA (ID_ENCOMENDA) ENABLE;  
 
CREATE TABLE LINHA_FACTURA 
   (	COD_FACTURA NUMBER(*,0) NOT NULL ENABLE, 
      COD_ARTIGO NUMBER(*,0) NOT NULL ENABLE,
      QUANTIDADE INTEGER NOT NULL ENABLE,
      PRECO_UNIT NUMBER NOT NULL ENABLE, 
      TAXA_IVA NUMBER(4,2) NOT NULL ENABLE
    ) ;
  ALTER TABLE LINHA_FACTURA ADD CONSTRAINT LINHA_FACTURA_PK PRIMARY KEY 
    (COD_FACTURA, COD_ARTIGO) ENABLE;
  ALTER TABLE LINHA_FACTURA ADD CONSTRAINT FK_LINHA_FACTURA_FACTURA FOREIGN KEY (COD_FACTURA)
	  REFERENCES FACTURA (COD_FACTURA) ENABLE;
  ALTER TABLE LINHA_FACTURA ADD CONSTRAINT FK_LINHA_FACTURA_ARTIGO FOREIGN KEY (COD_ARTIGO)
	  REFERENCES ARTIGO (COD_ARTIGO) ENABLE;

